import type { DecodedCustomId } from "../types.js";

/**
 * Component customId encoding scheme used by FlowMachine. Discord enforces a
 * 100-character limit, so the format is intentionally compact:
 *
 *     fs|<flowId>|<executionId>|<trigger>
 *
 * - `fs` is a fixed sentinel so unrelated component ids can be detected and
 *   safely ignored without an expensive parse.
 * - `executionId` is the running flow instance id.
 * - `trigger` is the event name dispatched into the state machine
 *   (e.g. `next`, `cancel`, `select-color`).
 */
const SEP = "|";
const PREFIX = "fs";
const MAX_LEN = 100;

/**
 * Encode a customId for the given flow execution.
 *
 * Throws synchronously if the resulting id would exceed Discord's hard 100
 * character limit; this is preferable to silently truncating and breaking the
 * decode roundtrip at runtime.
 */
export function encodeCustomId(
  flowId: string,
  executionId: string,
  trigger: string,
): string {
  if (flowId.includes(SEP) || executionId.includes(SEP) || trigger.includes(SEP)) {
    throw new Error(
      `flowstate: customId components must not contain "${SEP}" (got flowId="${flowId}", executionId="${executionId}", trigger="${trigger}").`,
    );
  }
  const id = `${PREFIX}${SEP}${flowId}${SEP}${executionId}${SEP}${trigger}`;
  if (id.length > MAX_LEN) {
    throw new Error(
      `flowstate: customId "${id}" exceeds Discord's 100-character limit (${id.length}). Shorten flowId or trigger names.`,
    );
  }
  return id;
}

/**
 * Decode a customId produced by {@link encodeCustomId}. Returns `null` for any
 * string that wasn't generated by flowstate (so callers can pass through to
 * other handlers).
 */
export function decodeCustomId(customId: string): DecodedCustomId | null {
  if (!customId.startsWith(`${PREFIX}${SEP}`)) return null;
  const parts = customId.split(SEP);
  if (parts.length !== 4) return null;
  const [, flowId, executionId, trigger] = parts;
  if (!flowId || !executionId || !trigger) return null;
  return { flowId, executionId, trigger };
}

/**
 * Check whether a customId was produced by flowstate without fully decoding it.
 * Useful as a fast-path filter inside an existing interactionCreate handler.
 */
export function isFlowstateCustomId(customId: string): boolean {
  return customId.startsWith(`${PREFIX}${SEP}`);
}
